### ISSUE TITLE
Error .view() for ligand

### ISSUE THREAD

**Issue by cuzzo87** [Acellera/moleculekit#59] opened 2020-11-04 11:49 UTC
Hi guys,

Here me again, I was playing around with the molecule object and trying to visualize the ligand.

```python
from htmd.molecule.molecule import Molecule
m = Molecule('4eiy')
lig = m.copy()
lig.filter('resname ZMA')
m.write('4eiy.pdb')
lig.write('zma.pdb')
lig.view()
lig.view()
m.reps.add('protein', 'NewCartoon', 8)
m.reps.add('resname ZMA', 'Licorice')
m.view()
```

The first image is the visualization of the initial molecule **m**.

![complexHTMD_ok](https://user-images.githubusercontent.com/10772443/98108114-c6435e00-1e9b-11eb-9d98-e405d53153e5.png)

The second image is the visualization of the molecule object for the ligand only **lig** obtained by the filter command.
![ligHTMD_error](https://user-images.githubusercontent.com/10772443/98108116-c6dbf480-1e9b-11eb-9561-b3e59874185b.png)

Finally, the last image is the ligand saved as pdb from the ligand object **lig** and then opened by vmd
![lig_VMD_ok](https://user-images.githubusercontent.com/10772443/98108118-c6dbf480-1e9b-11eb-8ff3-57aa6ee8b574.png)

**Comment by stefdoerr** [comment] 2020-11-04 12:39
I can't reproduce this. For me it visualizes fine. What version of HTMD/moleculekit are you using?

**Comment by stefdoerr** [comment] 2021-03-08 15:04
I think we can close this

**Closed by stefdoerr** 2021-03-08 15:04 UTC
