### ISSUE TITLE
SmallMol and SmallMolLib reading issues

### ISSUE THREAD

**Issue by j3mdamas** [Acellera/moleculekit#12] opened 2019-06-04 13:41 UTC
Taking on example from PDBBind refined set, `SmallMol` and `SmallMolLib` have issues. With Molecule:

```python
from moleculekit.molecule import Molecule
m = Molecule('1a1e_ligand.mol2')
```
works. With `SmallMol`:

```python
from moleculekit.smallmol.smallmol import SmallMol
sm = SmallMol('1a1e_ligand.mol2', removeHs=True, fixHs=True, force_reading=True)
```
works with:
```
[15:33:04] 1a1e_ligand: warning - O.co2 with non C.2 or S.o2 neighbor.
2019-06-04 15:33:04,717 - moleculekit.smallmol.smallmol - WARNING - Reading 1a1e_ligand.mol2 with force_reading procedure
```
but produces a molecule with an hydrogen completely out of place:
![vmdscene](https://user-images.githubusercontent.com/10810178/58883348-8c868a80-86de-11e9-8e99-5b0b73ce2476.png)

The `force_reading` is necessary to work. Combinations of `removeHs` and `fixHs` produce the same output.

With SmallMolLib and using the sdf instead:
```python
from moleculekit.smallmol.smallmollib import SmallMolLib
sml = SmallMolLib('1a1e_ligand.sdf')
```
fails with:
```
  0%|                                                     | 0/1 [00:00<?, ?it/s][15:38:20] Explicit valence for atom # 25 C, 6, is greater than permitted
[15:38:20] ERROR: Could not sanitize molecule ending on line 152
[15:38:20] ERROR: Explicit valence for atom # 25 C, 6, is greater than permitted

---------------------------------------------------------------------------
ArgumentError                             Traceback (most recent call last)
~/maindisk/SANDBOX/acemanager/latest_2019-05-02_11h59/lib/python3.6/site-packages/moleculekit/smallmol/smallmollib.py in sdfReader(file, removeHs, fixHs, isgzip)
     56         try:
---> 57             mols.append(SmallMol(mol, removeHs=removeHs, fixHs=fixHs))
     58         except:

~/maindisk/SANDBOX/acemanager/latest_2019-05-02_11h59/lib/python3.6/site-packages/moleculekit/smallmol/smallmol.py in __init__(self, mol, ignore_errors, force_reading, fixHs, removeHs)
    104         if fixHs:
--> 105             _mol = Chem.AddHs(_mol, addCoords=True)
    106 

ArgumentError: Python argument types in
    rdkit.Chem.rdmolops.AddHs(NoneType)
did not match C++ signature:
    AddHs(RDKit::ROMol mol, bool explicitOnly=False, bool addCoords=False, boost::python::api::object onlyOnAtoms=None)

During handling of the above exception, another exception occurred:

AttributeError                            Traceback (most recent call last)
<ipython-input-18-b44ad4f6fbb3> in <module>
----> 1 sml = SmallMolLib('1a1e_ligand.sdf')

~/maindisk/SANDBOX/acemanager/latest_2019-05-02_11h59/lib/python3.6/site-packages/moleculekit/smallmol/smallmollib.py in __init__(self, libfile, removeHs, fixHs)
    100     def __init__(self, libfile=None, removeHs=False, fixHs=True):  # , n_jobs=1
    101         if libfile is not None:
--> 102             self._mols = self._loadLibrary(libfile, removeHs=removeHs, fixHs=fixHs, ext=None)
    103 
    104 

~/maindisk/SANDBOX/acemanager/latest_2019-05-02_11h59/lib/python3.6/site-packages/moleculekit/smallmol/smallmollib.py in _loadLibrary(self, libfile, removeHs, fixHs, ext)
    112 
    113         if ext == '.sdf':
--> 114             return sdfReader(libfile, removeHs, fixHs, isgzip)
    115         elif ext == '.smi':
    116             return smiReader(libfile, removeHs, fixHs, isgzip)

~/maindisk/SANDBOX/acemanager/latest_2019-05-02_11h59/lib/python3.6/site-packages/moleculekit/smallmol/smallmollib.py in sdfReader(file, removeHs, fixHs, isgzip)
     57             mols.append(SmallMol(mol, removeHs=removeHs, fixHs=fixHs))
     58         except:
---> 59             if mol.HasProp('_Name'):
     60                 name = mol.GetProp('_Name')
     61             print('Failed to load molecule{}. Skipping to next molecule.'.format(' with name {}'.format(name)))

AttributeError: 'NoneType' object has no attribute 'HasProp'
```
The files: [1a1e.zip](https://github.com/Acellera/moleculekit/files/3252658/1a1e.zip)

**Comment by stefdoerr** [comment] 2019-06-04 13:59
Report `rdkit` version because I don't trust you guys anymore, updating to some new stuff that's broken :P

**Comment by j3mdamas** [comment] 2019-06-04 14:07
```
[joao@computer02 ~]$ conda list | egrep rdkit
rdkit                     2017.09.2.0      py36hf4eed20_1    acellera
```
I don't see any limitation on rdkit version on the repo though

**Comment by stefdoerr** [comment] 2019-06-04 14:14
Ok that one should work. There is no limitation but we only ship that one from acellera so by default you cannot get a newer one unless you try to be clever. In any case, this seems like an rdkit issue, not a moleculekit one.

**Comment by stefdoerr** [comment] 2019-06-04 18:13
I see, the issue is in the hydrogen fixing of rdkit.
If you do this it works fine. 
```python
sm = SmallMol('1a1e_ligand.mol2', force_reading=True, removeHs=False, fixHs=False)
```
The fixing puts the hydrogen at [0, 0, 0] coordinates. 

My suggestion for the moment would be to try to protonate the molecules with some other software and then load the mol2 with all the hydrogens using SmallMol and the above options.

**Comment by stefdoerr** [comment] 2019-06-04 18:44
@j3mdamas I fixed the error when trying to read the sdf. Now it correctly just prints the rdkit error and reports that it failed to load the molecule 
https://github.com/Acellera/moleculekit/commit/12b60abb3c2bda12dac0f20765ca90c20ca89543

**Comment by stefdoerr** [comment] 2019-06-04 18:45
```python
In [1]: from moleculekit.smallmol.smallmollib import SmallMolLib 
   ...: sml = SmallMolLib('1a1e_ligand.sdf')                                                                        
  0%|                                                                                         | 0/1 [00:00<?, ?it/s][21:41:48] Explicit valence for atom # 25 C, 6, is greater than permitted
[21:41:48] ERROR: Could not sanitize molecule ending on line 152
[21:41:48] ERROR: Explicit valence for atom # 25 C, 6, is greater than permitted
100%|████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 104.12it/s]
2019-06-04 21:41:48,718 - moleculekit.smallmol.smallmollib - INFO - Failed to load 1/1 molecules
```

**Comment by stefdoerr** [comment] 2019-06-04 18:55
Added option to disable rdkit sanitization of the sdf files:
```
In [1]: from moleculekit.smallmol.smallmollib import SmallMolLib                                                    

In [2]: sml = SmallMolLib('1a1e_ligand.sdf', fixHs=False, removeHs=False, sanitize=True)                            
  0%|                                                                                         | 0/1 [00:00<?, ?it/s][21:54:01] Explicit valence for atom # 25 C, 6, is greater than permitted
[21:54:01] ERROR: Could not sanitize molecule ending on line 152
[21:54:01] ERROR: Explicit valence for atom # 25 C, 6, is greater than permitted
100%|█████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 70.80it/s]
2019-06-04 21:54:01,950 - moleculekit.smallmol.smallmollib - INFO - Failed to load 1/1 molecules

In [3]: sml = SmallMolLib('1a1e_ligand.sdf', fixHs=False, removeHs=False, sanitize=False)                           
100%|████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 215.58it/s]
```

**Comment by stefdoerr** [comment] 2019-06-04 18:57
So to conclude, after fixing the minor aesthetics issues here, rdkit hates this molecule. It doesn't want to sanitize it and doesn't want to fix the hydrogens. @cuzzo87 if you want take a look at the molecule to see if there is something peculiar about it and if it's normal I'd open an issue on the rdkit issue tracker.

**Comment by stefdoerr** [comment] 2019-06-04 19:08
who made these `mol2/sdf` files? They have the S and C marked as double or aromatic bonds to all oxygens! That's why rdkit fails.
![image](https://user-images.githubusercontent.com/7935362/58906572-df7b3480-8714-11e9-93c8-a5945bb8eec4.png)

**Comment by stefdoerr** [comment] 2019-06-04 19:28
So my conclusion is that input files are simply broken. Either the atom types are bad or the bonds are bad. This causes rdkit to fail and in my opinion it gives decent warnings ala `[22:12:23] 1a1e_ligand: warning - O.co2 with non C.2 or S.o2 neighbor`. If someone can provide the source of these files or how they were generated it would be great, otherwise I will close the issue.

**Comment by BioFreak95** [comment] 2019-06-05 07:04
The data are from the PDBbind-dataset. This is the dataset, which was used in the KDeep-paper of your group. Because I want to reproduce the results of the paper as baseline for masterthesis, I have to use this data. You can get the data here http://pdbbind.org.cn/. In this case, this are data from the refined set of 2016.

From around 3700 data for the training-set of the NN, 1200 leads to this errors.
One of the supporter of the HTMD has said, that during the dev of this paper, no SmallMolecule class was avaible and I should use the Molecule-class instead. Like mentioned in issue #13 this seems not as a good idea. So how I can get the voxelized data for the NN with your software?

`sm = SmallMol('1a1e_ligand.mol2', force_reading=True, removeHs=False, fixHs=False)`

This kind of stuff is working for some of the data. The first question I have is maybe a little bit stupid, but there are hydrogen in the files. Does this not mean, that they are allready protonated?

But nevertheless, there are some files, which I can not read in, also with this trick. For example the complex "1ols" failed to read with this.

So in general, there must be an option, to get the voxelised data with features for the ligands, to reproduce the results of KDeep. In the paper they mentioned, that HTMD is the software, which can be used to get these. But actually I can not see, how I can do this. Or better how should do this.

Maybe you have an idea, what is the fastest way to get the voxelised data for the network.


So this comment is an combination from this issue and the closed issue #13.

**Comment by stefdoerr** [comment] 2019-06-05 07:39
I'm sorry but I cannot help you clean the PDBbind dataset. To me the dataset looks pretty broken.
![image](https://user-images.githubusercontent.com/7935362/58937627-a3c78580-877b-11e9-9634-d8e8c193ee04.png)
Look at the hydrogens at the right, they are all over the place.
So the hydrogens are wrong, and you cannot remove+guess them with rdkit because the atom types and the bonds are wrong as well.

with the latest github version of moleculekit you can read the sdf files like this:
```python
allmols = []
for ff in glob('./*.sdf'):
    allmols.append(SmallMolLib(ff, sanitize=False, removeHs=False, fixHs=False)[0])
```
But I don't see the point in reading them in with the hydrogens as they are wrong.

Only thing I can suggest you is to find some software that can fix the bond types and the hydrogens of the ligands and then read it in with smallmol. Maybe autodock tools can do it since we used that for the paper.

**Comment by BioFreak95** [comment] 2019-06-05 08:00
Is the dev of the KDeep related to moleculekit? Maybe he can help with an short introduction, how he have done this? Maybe there is an very easy path in autodock for this? I never used autodock before, so I do not know.

**Comment by stefdoerr** [comment] 2019-06-05 08:03
http://autodock.scripps.edu/faqs-help/how-to/how-to-prepare-a-ligand-file-for-autodock4

**Comment by stefdoerr** [comment] 2019-06-05 08:04
Thinking about it, this will not really work. Autodock has it's own atom types and pdbqt format which rdkit cannot read. You need to find some other way to fix the hydrogens and bonds in PDBbind.

**Comment by BioFreak95** [comment] 2019-06-05 08:17
Well. But the old version of HTMD want to have ptbqt for the getVoxelDescriptor(). So I could use the old version for the ligands and use this script to transform ligands in ptbqt.
But nevertheless, in general, I need a fixed version of the files for further projects.

**Comment by BioFreak95** [comment] 2019-06-05 08:31
Maybe one could use this prepare_ligand and then convert the pdbqt back to a mol2 file.
I have no idea if this is working, but I would try. 
If this is working, I would add a comment here. Maybe one could create a python function out of this procedure and integrate this in HTMD. For the future, this could be helpful.

**Comment by stefdoerr** [comment] 2019-06-05 08:32
Yes, you can use the above script I posted to prepare the ligands with autodock, it also has one for proteins. Then load them with Molecule and use `getVoxelDescriptors` with `version=1`

**Comment by stefdoerr** [comment] 2019-06-05 08:33
I doubt you will be able to convert the pdbqt to a working mol2 file. `rdkit` is peculiar about the atomtypes it wants.

**Comment by BioFreak95** [comment] 2019-06-05 15:51
Maybe a small info.
I wrote a function, which uses pybel and firstly convert the mol2 file 
to a pdbqt format.
After this, it convert the pdbqt in a pdb-file.
This can be read in with the SmallMol-class, without force-reading.

For all SmallMols I can create the voxelised features.

There is an exception for one ligand file. I do not know, why it fails. 
But 1 of 3700 is better than 1380 of 3700.

Actually also the proteins leads to some errors. Maybe we can shortly 
discuss this.

I use the following Code:
`
prot = Molecule(Path_To_Prot)
prot.filter('protein')
prot.bonds = prot._getBonds()
voxeldescriptors.getVoxelDescriptors(prot)
`

This results in the error boolean index did not mathc indexed array 
along dimension 0,
dimension is 234 but corresponding booleand dimesnion is 4644

If I use:
`
prot = Molecule(Path_To_Prot)
prot.filter('protein')
prot.bonds = prot._getBonds()
prot = prepareProteinForAtomtyping(prot)
voxeldescriptors.getVoxelDescriptors(prot)
`

I get the following error:

`  File "/home/max/anaconda3/lib/python3.6/site-packages/moleculekit/tools/voxeldescriptors.py", line 195, in getVoxelDescriptors
    channels, mol = getChannels(mol, aromaticNitrogen, version, validitychecks)
  File "/home/max/anaconda3/lib/python3.6/site-packages/moleculekit/tools/voxeldescriptors.py", line 90, in getChannels
    sigmas = _getChannelRadii(mol.get('element'))
  File "/home/max/anaconda3/lib/python3.6/site-packages/moleculekit/tools/voxeldescriptors.py", line 61, in _getChannelRadii
    radii = np.array([periodictable[e].vdw_radius for e in molelements])
  File "/home/max/anaconda3/lib/python3.6/site-packages/moleculekit/tools/voxeldescriptors.py", line 61, in <listcomp>
    radii = np.array([periodictable[e].vdw_radius for e in molelements])
KeyError: 'SE'`

Maybe you have an idea.

**Comment by BioFreak95** [comment] 2019-06-05 15:56
The point is in general, that the prepareProtein-function changes the molecule. In KDeep, binding affinities are predicted. If I change the protein in some way, then the binding-affinity is maybe not correct anymore.

This could also mean, that if some bounds or hydrogens are fixed in AutoDock4, that the binding-affinities are not correct to the "fixed" molecule. Because you do not know, which bondtype is wrong and which you have to fix. Same for hydrogens.

Maybe here could just the deactivation of validitychecks help? Just put this stuff in the voxelisation? What do you think about this.

I would write the pdbbind-support a mail and would inform them. Maybe they also have an idea.

BTW. The error-message above is from the protein of complex "1gz4" of the dataset

**Comment by BioFreak95** [comment] 2019-06-06 07:50
Well. Some of the errors with this dataset for the proteins can be solved by converting. 

The error with the 'SE' is, that the software reads Selenium sometimes with SE instead of Se. I do not know why, but it can fixed for my data with `prot.set(value='Se', field = 'element', sel='name SE')`.

I tested acutally 500 complexes. With this two points, I could fix all but of of them which raises an error.

Maybe a much more interesting part would be, that at one of my files (of my tested, actually I do not have tested all 3700 complexes) has the problem that if I prepare the protein before voxelisation  with `prot = prepareProteinForAtomtyping(prot)`. Leads to the error.

_~/anaconda3/lib/python3.6/site-packages/moleculekit/tools/voxeldescriptors.py in getChannels(mol, aromaticNitrogen, version, validitychecks)
     83         elif version == 2:
     84             from moleculekit.tools.atomtyper import getFeatures, getPDBQTAtomTypesAndCharges
---> 85             mol.atomtype, mol.charge = getPDBQTAtomTypesAndCharges(mol, aromaticNitrogen=aromaticNitrogen, validitychecks=validitychecks)
     86             channels = getFeatures(mol)
     87 

~/anaconda3/lib/python3.6/site-packages/moleculekit/tools/atomtyper.py in getPDBQTAtomTypesAndCharges(mol, aromaticNitrogen, validitychecks)
    163     charges = ['{0:.3f}'.format(a[-1]) for a in atomsProp]
    164     pdbqtATypes = [getPDBQTAtomType(a[3], n, mol, aromaticNitrogen)
--> 165                    for n, a in enumerate(atomsProp)]
    166 
    167     return np.array(pdbqtATypes, dtype='O'), np.array(charges, dtype='float32')

~/anaconda3/lib/python3.6/site-packages/moleculekit/tools/atomtyper.py in <listcomp>(.0)
    163     charges = ['{0:.3f}'.format(a[-1]) for a in atomsProp]
    164     pdbqtATypes = [getPDBQTAtomType(a[3], n, mol, aromaticNitrogen)
--> 165                    for n, a in enumerate(atomsProp)]
    166 
    167     return np.array(pdbqtATypes, dtype='O'), np.array(charges, dtype='float32')

~/anaconda3/lib/python3.6/site-packages/moleculekit/tools/atomtyper.py in getPDBQTAtomType(atype, aidx, mol, aromaticNitrogen)
     53         # print(aidx)
     54         # print(np.where(mol.bonds == aidx))
---> 55         bond = np.where(mol.bonds == aidx)[0][0]
     56         oidx = [a for a in mol.bonds[bond] if a != aidx][0]
     57         if mol.element[oidx] not in ['C', 'A']:

IndexError: index 0 is out of bounds for axis 0 with size 0_

Without perparation it works. Is this a Bug in the preperation-function?

**Comment by stefdoerr** [comment] 2019-06-07 13:52
Which version are you using of moleculekit? The issue with the element names is solved as far as I'm concerned in the last version.

Don't disable the validity checks. The option is only there for performance reasons if all your data is already perfect and you don't want to waste time doing the checks.

The error you get means that there are no bonds in the molecule which is very weird. Do a `%debug` when it throws the error in `ipython` and check what the `mol` object contains and do `mol.view(guessBonds=False)` which will show the structure with the bonds it contains (probably not bonds, just dots in space). Then you can figure out why the bond guessing failed. My guess is that the structure is probably broken or empty.

Also as a general suggestion to get better answers online, keep the error reports a bit more concise otherwise it's hard to answer to so many questions over so many posts. Thanks anyway for the interest and the reports :)

**Comment by BioFreak95** [comment] 2019-06-07 17:16
I use the last version. Maybe this is a bug, but I think not part of this ticket. For me I have found a solution to fix this.

For the bond-guessing error, this comes from the prepareprotein-method. The not prepared protein passes all validitychecks. But this seems as an very rare event. I can not say, if this is a bug. But also here I "fix" this and do not use the prepare function for the small number of proteins.

Thank you for your help. Next time I will pay attention to this.

**Comment by stefdoerr** [comment] 2019-06-14 13:12
Ok I could replicate the selenium issue. The proteinPrepare was reading the elements from pdb2pqr and not capitalizing them correctly.

I fixed it here https://github.com/Acellera/moleculekit/commit/c9af624a0943e105b754bc252f16bd40157f39c2
Thanks a lot for the report!

**Comment by stefdoerr** [comment] 2019-06-14 13:14
@BioFreak95 which protein was giving issues with the bonds? I could give that a look as well. 1gz4 seems to work fine after my fix for the element guessing.

**Comment by BioFreak95** [comment] 2019-06-16 13:42
Ah very nice. Thank you for the fix.
Two examples for the proteins are 1mmr and 3bxh.

**Comment by stefdoerr** [comment] 2019-06-21 11:14
Thanks for the report! I checked the proteins and it's an issue of `proteinPrepare` which is adding missing sidechains to the structure but so close that the bond guessing thinks they are bonded
![image](https://user-images.githubusercontent.com/7935362/59918974-e3a29400-942e-11e9-8cde-9c1f8816d6f0.png)
I'll need to summon @tonigi for this

**Comment by BioFreak95** [comment] 2019-06-21 11:34
Oh. Very nice, that you found the mistake. If you can fix this, it would be very great and helpful for me.

Do you think, it is doable and if yes, how long you will need. Can you make a rough assumption?

**Comment by tonigi** [comment] 2019-06-21 11:37
No estimation for a fix time. But, as a workaround, you may filter out the offending (or all) sidechains.

**Comment by stefdoerr** [comment] 2019-06-21 11:51
`pdb2pqr` is not our software unfortunately. I think the best solution would be to somehow else get the sidechains. For example if you build it with `charmm` or `amber` in HTMD. This would do a better job at guessing the sidechain positions and give you the correct bonds

**Comment by BioFreak95** [comment] 2019-06-21 11:52
I have 3700 Proteins, so I have to calc this automatical, deleting the broken sidechains, would mean, that I have to check all proteins manually. I think deleting all sidechains sounds, as it would have a big influence on the voxel-features.

Am I right? Or did I missunderstanding something?

**Comment by tonigi** [comment] 2019-06-21 11:54
Do you pass through the `build()` phase? If yes, feel free to delete the sidechains. The system-specific builders will re-add them. Otherwise, you may want to only remove them in presence of clashes.

**Comment by stefdoerr** [comment] 2019-06-21 11:58
@BioFreak95 try to build all the proteins (or the ones that fail better since it's slow) with charmm or amber.  This will fix your issues.

**Comment by BioFreak95** [comment] 2019-06-21 12:02
I have to say, that I did not know, how I can check if I am before or after the build phase. 

So the Error raises not in the prep, it raises in the getVoxeldescriptor(). So the validitychecks fails.

But maybe I can fix this in the broken Proteins. I can catch them and I think, there are maybe 20-30, which breakes. Do only check on third, till now.

**Comment by stefdoerr** [comment] 2019-06-21 12:06
You are not building currently. Toni didn't know you were doing voxel stuff which doesn't build by defauit.
I would suggest the following order
1. Load molecule
2. Filter non-protein atoms out
2. Use proteinPrepare (not prepareProteinForAtomtyping)
3. Build with HTMD
4. Optionally: use prepareProteinForAtomtyping if necessary
5. Do voxelization

**Comment by stefdoerr** [comment] 2019-06-21 12:08
A more complex example on how to build is here:
https://software.acellera.com/docs/latest/htmd/tutorials/system-building-protein-ligand.html

**Comment by stefdoerr** [comment] 2019-06-21 12:09
You can skip most steps since you are just building a protein without water.
Just use proteinPrepare, autoSegment and then `charmm.build` or `amber.build` with `ionize=False` and it should work

**Comment by BioFreak95** [comment] 2019-06-21 12:11
Building means htmd.molecule(prot)? Or did you have a special expression in htmd for this?

**Comment by stefdoerr** [comment] 2019-06-21 12:14
```
from htmd.ui import *
mol = Molecule('1mmr')
mol.filter('protein')
pmol = proteinPrepare(mol)
pmol = autoSegment(pmol)
bmol = charmm.build(pmol, ionize=False)
```
This worked for me

**Comment by stefdoerr** [comment] 2019-06-21 12:15
I mean if you manage to build them all, even better. But it can be time-consuming for large proteins

**Comment by stefdoerr** [comment] 2019-06-21 12:18
But avoid bond-guessing after that! `prepForAtomtyping` will guess bonds and might mess it up again.

**Comment by BioFreak95** [comment] 2019-06-21 12:21
Great. So if this is too time consuming, just

prot =Molecule(...)
prot.filter('protein')
Prot = PrepareProteinForAtomtyping(prot)
Voxel = getVoxeldescriptor(...)


For the broken,

mol.filter('protein')
pmol = proteinPrepare(mol)
pmol = autoSegment(pmol)
bmol = charmm.build(pmol, ionize=False)
Voxel = ...

**Comment by stefdoerr** [comment] 2019-06-21 13:20
Yes, if you look at `PrepareProteinForAtomtyping` it does more or less the same stuff I wrote for building but without building.

**Comment by BioFreak95** [comment] 2019-06-21 13:30
Great. Thank you very much for this tips. I think, that make sthe preprocessing much easier. I will test this, this weekend :-)

**Comment by BioFreak95** [comment] 2019-06-25 20:27
OK. This is working for all in spite of 6 proteins.
3 of them I could fix by converting it to mol2. I have no idea, why this works, but it works.

The last 3 I could not fix. Maybe you have an idea.
4bcn and 4bcp have with the old variant the again the error of "index 0 is out of bounds for axis 0 with size 0", so I have done what you said and used the build-variant.
But then an error raises:

> UnknownResidueError("Unknown residue(s) ['TPO'] found in the input structure. You are either missing a topology definition for the residue or you need to rename it to the correct residue name",)
> Check /home/max/Documents/Masterarbeit/build/log.txt for further information on errors in building.
> 

For 4bps I have always float division by zero.
Maybe you can test this on your system and have an idea, how this can be solved.

**Comment by stefdoerr** [comment] 2019-06-25 21:02
TPO is a [phosphothreonine](http://www.ebi.ac.uk/pdbe/entry/pdb/1h1q/modified/TPO). If the TPO is not in the binding pocket feel free to mutate it to whatever residue you feel like (VAL might be best since it's tiny) with `mol.mutateResidue` right after loading the molecule.

**Comment by stefdoerr** [comment] 2019-06-25 21:17
4bps gives me a build error that it's missing `MSE` which is a [selenomethionine](https://www.ebi.ac.uk/pdbe/entry/pdb/1vi9/modified/MSE) which I would mutate to a `MET` since these only exist for technical crystallography reasons and should not be there.
It also contains `3EB` which is a ligand but somehow considered as part of the protein so I had to remove it explicitly.

Generally a good idea to look at the small molecules section of the PDB
https://www.rcsb.org/structure/4BPS
I managed to build it like this.
```
mol = Molecule('4bps')
mol.filter('protein')
pmol = proteinPrepare(mol)
pmol = autoSegment(pmol)
pmol.filter('not resname 3EB')
pmol.mutateResidue('resname MSE', 'MET')
bmol = charmm.build(pmol, ionize=False)
```

**Comment by BioFreak95** [comment] 2019-06-25 22:20
Thanks.

I think, that TOP is in the binding pocket :/
Does it change the behavior strong if I change it to THR? Do you have exp. with this?

Did you get the Division by zero error? 4bps raises this by using proteinPrepare() on my machine.

**Comment by stefdoerr** [comment] 2019-06-26 07:31
No, didn't get any division by zero.
If you "mutate" the TPO to THR it will remove the sidechain and remodel it as it sees fit, meaning the coordinates will change.
If you want to keep it as TPO check the answer here: https://www.researchgate.net/post/Where_can_I_find_forcefields_for_phosphoserine_to_use_with_NAMD
You need to patch the residue (you can pass patch commands to charmm.build). But then you might have to remove the phospho tail before patching so that psfgen can add it explicitly, I've never tried it.
In any case I think you won't avoid modifying the coordinates, sorry. So either skip it or hope it doesn't modify the interactions strongly

**Comment by stefdoerr** [comment] 2019-06-28 14:19
Ok I think this issue can be closed now. The issues with the reading have been resolved and the discussion has gone over to how to build with HTMD which can be continued (if necessary on the HTMD issue tracker). Unfortunately I cannot replicate the division by zero so it seems a machine specific issue.
Thanks for the report and the persistence which helped fix some bugs and iron out the details :) If you have any other issues feel free to open a new one.

**Closed by stefdoerr** 2019-06-28 14:19 UTC
Labels: bug
