### ISSUE TITLE
Molecules in getVoxelDescriptors()

### ISSUE THREAD

**Issue by BioFreak95** [Acellera/moleculekit#13] opened 2019-06-04 17:36 UTC
Hi devs,

I have a short question to the Topic getVoxelDescriptors. Like mentioned in Issue #12, sometimes it is not possible to create a SmallMol. I am trying to reproduce the KDeep-paper. You said me already, that during the dev of the paper, the SmallMol-Class does not exist and you use the Molecule-Class.

Well If I create the Molecule class from a ligand, than I get an Error in getVoxelDescriptor(), that my Mol is not a protein.
Is the only option, the deactivation of the validitychecks?
How I get a similar result like it was used in the 'old' package. 

If this is not possible, I think I have to use the old version of the package. But then I need to have my data in the ptbqt-format form AutoDock4. Can you give me a hint, how you have converted the files in the ptbqt-format?

**Comment by stefdoerr** [comment] 2019-06-04 17:45
Do you have concrete cases that SmallMol does not work? Could you post them here? In the paper we used autodock to get the features but we have dropped this since then to be more independent and have better control. We have been able to reproduce it afaik with SmallMol.

**Comment by stefdoerr** [comment] 2019-06-04 17:49
Also no, don't disable the validity checks. You will just get garbage out if you pass a small molecule with as a Molecule object in.

**Comment by BioFreak95** [comment] 2019-06-04 17:56
Well the problem with the SmallMol is mentioned in Issue #12. There is also a file as example. In general, from the ca 3700 Complexes of the refined dataset of pdbbind, around 1200 ligands can not be readed in as SmallMol.
The reason is in rdkit. So at the problematic ligands, it is not possible to create a molecule-object in rdkit and because of this, it is not possible to create a SmallMol with moleculekit or HTMD.

The support of accelera, said that I can use Molecule instead of SmallMolecule. But like you mentioned, I would need to disable the validitychecks.

**Comment by stefdoerr** [comment] 2019-06-04 18:08
Ok, let's continue in the other issue then for now

**Comment by stefdoerr** [comment] 2019-06-04 19:29
@BioFreak95 I will close this issue as you should not use Molecule for small molecules in getVoxelDescriptors. Check #12 to see my analysis of the issue with the problematic molecule.

**Closed by stefdoerr** 2019-06-04 19:29 UTC
